### ISSUE TITLE
Moving license from GPL-2.0 to Apache 2.0 License

### ISSUE THREAD

**Issue by Geeks-Sid** [bgilbert/anonymize-slide#10]
Hi @bgilbert,

We are interested in using your anonymize-slide in one of our projects. However, we have encountered a licensing issue that prevents us from doing so. We would like to inquire whether you have any plans to change the current license (GPL-2.0) or to convert it to the Apache 2.0 License, which would provide us with more flexibility.

Alternatively, would it be possible for you to grant us a waiver to use your anonymize-slide? This would be immensely beneficial to the community, as it would allow us to continue using this project without any legal complications.

Thank you for your consideration.

**Comment by bgilbert** [comment]
Could you explain the problem you're facing?  If you invoke anonymize-slide as a separate program, its GPL license shouldn't affect any of your code.  You'd just need to distribute the source code for anonymize-slide along with your software, or otherwise make its code available according to the license, and you'd be set.

**Comment by sarthakpati** [comment]
Hi @bgilbert,
 
Thank you for your response! 
 
> If you invoke anonymize-slide as a separate program, its GPL license shouldn't affect any of your code. 
 
We want to modify (and extend) the code that you have written, and as such want to invoke it from a functional level and not just from the command line. 
 
> You'd just need to distribute the source code for anonymize-slide along with your software
 
We would want to cover our bases (not just immediately in the short term but also in the longer term when other people use our code). From a longer-term perspective, we are not sure if adding this requirement would cause (legal) hurdles to crop up (happy to discuss in detail via email). From all of these perspectives, it would be the easiest solution if you could either make this code available to use on a license that is not part of the GPL family (specifically, MIT or Apache), or if you can grant us permission in an email to use this specific version of the code with a different license.

Looking forward to hearing from you.

Cheers,
Sarthak

**Comment by bgilbert** [comment]
If you'd like to send additional details, feel free to use the email address in my profile.  However, I'd only consider changing the license if I felt that doing so would advance the interests of free software as a whole.  As I'm sure you can understand, my use of the GPL license here was an intentional choice.

**Comment by bgilbert** [comment]
I'll close this due to lack of response.  With genuine sincerity: thank you for respecting the license of this software.

**Comment by sarthakpati** [comment]
No worries! We have been debating this internally, and the consensus is that we will respect your choice of license and use some other solution. Cheers!
